name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Python 3.8
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8

    - name: Setup environment
      run: |
        pip install tox

    - name: Run linting check
      run: tox -e "lint"
    
    - name: Run unit tests
      run: tox -e "unit"

    - name: Package function
      run: |
        mkdir -p .tmp/azure-web-img-dwnszr
        cp -r host.json local.settings.json .tmp/
        pip install  --target=".tmp/.python_packages/lib/site-packages"  -r requirements.txt
        cp -r azure-web-img-dwnszr/* .tmp/azure-web-img-dwnszr/
        cd .tmp; zip -r ../azure-web-img-dwnszr.zip .*; cd ..
        rm -rf .tmp

    - name: Run end to end tests
      run: |
        az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" -t "$ARM_TENANT_ID"
        az account set --subscription "$ARM_SUBSCRIPTION_ID"
        rm -rf $AZURE_EXTENSION_DIR/eventgrid
        az extension add --n eventgrid
        exec -l $SHELL
        tox -e "e2e"
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.E2E_RESOURCE_GROUP_NAME }}
