name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set Python 3.8
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8

    - name: Setup environment
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run linting check
      run: tox -e "lint"
    
    - name: Run unit tests
      run: tox -e "unit"
    
    - name: Run end to end
      run: |
        az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" -t "$ARM_TENANT_ID"
        az account set --subscription "$ARM_SUBSCRIPTION_ID"
        tox -e "e2e"
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.E2E_RESOURCE_GROUP_NAME }}