name: Add files to release

on:
  release:
    types: [ published ]
    branches: [ master ] 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Python 3.8
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.8

    - name: Package function
      run: |
        mkdir -p .tmp/azure-web-img-dwnszr
        cp -r host.json local.settings.json .tmp/
        pip install  --target=".tmp/.python_packages/lib/site-packages"  -r requirements.txt
        cp -r src/* .tmp/azure-web-img-dwnszr/
        cd .tmp; zip -r ../azure-web-img-dwnszr.zip .*; cd ..
        rm -rf .tmp

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./azure-web-img-dwnszr.zip
        asset_name: azure-web-img-dwnszr-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
